# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Dump GitHub context
        env:
          GITHUB_CONTECT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"

      # Runs a set of commands using the runners shell
      - name: Get one context by env
        env: 
          TestContext: github.head_ref  
        run: echo "$TestContext"
      
      - name: Directly use contex
        run:  echo "$github.head_ref"
        
          
